### PR TITLE
chore: updating CODEOWNERS

### PR DESCRIPTION
**Pull request by Freyskeyd**
# Description

Updates the `CODEOWNERS` file for better control over the reviewers.

## PR Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added or updated tests that comprehensively prove my change is effective or that my feature works

### CODE REVIEW

**Review by muursh — CHANGES_REQUESTED** [review]
We shouldn't have such a broad group able to approve PRs here. If we want a team then we can create a team for this specifically but I am against this change as is

**Comment by Freyskeyd** [comment]
> We shouldn't have such a broad group able to approve PRs here. If we want a team then we can create a team for this specifically but I am against this change as is

I quite don't understand what you mean, this is a new [team](https://github.com/orgs/AggLayer/teams/agglayer-developers/members) which is a child team of [polygon-developers](https://github.com/orgs/AggLayer/teams/polygon-developers), but it doesn't mean that the parent team is `codeowner` nor have write permission on the repository.

**Comment by muursh** [comment]
> > We shouldn't have such a broad group able to approve PRs here. If we want a team then we can create a team for this specifically but I am against this change as is
> 
> I quite don't understand what you mean, this is a new [team](https://github.com/orgs/AggLayer/teams/agglayer-developers/members) which is a child team of [polygon-developers](https://github.com/orgs/AggLayer/teams/polygon-developers), but it doesn't mean that the parent team is `codeowner` nor have write permission on the repository.

I didn't realise the original team was called `polygon-developers` not `agglayer-developers` in my mind it was `agglayer-developers`. I'm still against this change as is though.

**Comment by Freyskeyd** [comment]
> I didn't realise the original team was called `polygon-developers` not `agglayer-developers` in my mind it was `agglayer-developers`. I'm still against this change as is though.

For which reason are you against ? Can you develop a little bit ?

**Review by muursh — APPROVED** [review]
I still think Theo should be there but I guess this is okay

**Pull request merged**
